# Arrays
## Basics

In [1]:
import array as arr

In [2]:
a=arr.array('i',[4,1,3])    #creating an array a
a

array('i', [4, 1, 3])

In [3]:
b=arr.array('i',[9,7,0])    #creating an array b
b

array('i', [9, 7, 0])

In [ ]:
## Slicing

In [4]:
a[1:]     #slicing

array('i', [1, 3])

In [6]:
a[::-1]    #reverse

array('i', [3, 1, 4])

In [11]:
a.append(2)
a

array('i', [4, 1, 3, 2, 2, 2])

In [12]:
a.pop(1)
a

array('i', [4, 3, 2, 2, 2])

In [13]:
a.remove(2)
a

array('i', [4, 3, 2, 2])

In [14]:
for i in a:
    print(i,end=" ")

4 3 2 2 

In [15]:
a+b   #contentation

array('i', [4, 3, 2, 2, 9, 7, 0])

In [ ]:
## Numpy

In [16]:
import numpy as np

In [18]:
h=np.array([(9,4,1),(8,7,6)])
s=np.array([(1,2,3),(4,5,6)])
h

array([[9, 4, 1],
       [8, 7, 6]])

In [19]:
s

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
h.ndim   #to check the dimension in h

2

In [21]:
s.ndim   #to check the dimension in s

2

In [22]:
h.itemsize   #to know size of the element of h

4

In [23]:
h.dtype     #data type of h

dtype('int32')

In [24]:
s.dtype    #data type of s

dtype('int32')

In [25]:
h.size   

6

In [26]:
h.shape    #finding number of rows and columns of h

(2, 3)

In [28]:
h.reshape(3,2)  #changing rows and columns of h

array([[9, 4],
       [1, 8],
       [7, 6]])

In [29]:
h.min()       #to find minimum value of h

1

In [30]:
s.min()      #to find minimum value of s

1

In [31]:
h.max()      #to find maximum value of h

9

In [32]:
s.max()       #to find maximum value of s

6

In [33]:
h.sum()       #to find sum of h matrix 

35

In [35]:
i=np.linspace(3,8,10) #getting 10 values between 3 and 8
i

array([3.        , 3.55555556, 4.11111111, 4.66666667, 5.22222222,
       5.77777778, 6.33333333, 6.88888889, 7.44444444, 8.        ])

In [36]:
h.sum(axis=0)      #sum of elements in column wise

array([17, 11,  7])

In [37]:
h.sum(axis=1)      #sum of elements in row wise

array([14, 21])

In [38]:
np.sqrt(h)         #square root of elements in h 

array([[3.        , 2.        , 1.        ],
       [2.82842712, 2.64575131, 2.44948974]])

In [39]:
np.std(h)          #standard deviation for h

2.6718699236468995

In [40]:
np.mean(h)        #mean of the elements

5.833333333333333

In [43]:
h

array([[9, 4, 1],
       [8, 7, 6]])

In [46]:
h[0,2]    #finding 2nd element of oth column

1

In [47]:
h[0:2,1]

array([4, 7])

In [48]:
h[h>1]

array([9, 4, 8, 7, 6])

In [50]:
h[h!=4]

array([9, 1, 8, 7, 6])

In [51]:
h.sort()       #sorting elements in ascending order
h

array([[1, 4, 9],
       [6, 7, 8]])

In [52]:
h+s            #addition of matrices

array([[ 2,  6, 12],
       [10, 12, 14]])

In [53]:
h%s 

array([[0, 0, 0],
       [2, 2, 2]], dtype=int32)

In [54]:
h-s           #subtraction of matrices

array([[0, 2, 6],
       [2, 2, 2]])

In [56]:
h*s     #multiplication of matrices

array([[ 1,  8, 27],
       [24, 35, 48]])